/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex('properties').del();
  await knex('properties').insert([
    {
      id: 'prop-001',
      title: 'Division Road house',
      price: 250000,
      location: 'Ha Noi',
      category: 'house',
      type: 'for-sale',
      bedrooms: 3,
      bathrooms: 2,
      garages: 3,
      area: 1200,
      status: 'For sale',
      image_url: 'https://picsum.photos/seed/prop-001/600/400',
      description: 'Charming house on Division Road with spacious backyard and modern interior.',
      agent_id: 'agent-001',
    },
    {
      id: 'prop-002',
      title: 'North Road house',
      price: 222000,
      location: 'TP HCM',
      category: 'house',
      type: 'for-sale',
      bedrooms: 2,
      bathrooms: 3,
      garages: 1,
      area: 1200,
      status: 'For sale',
      image_url: 'https://picsum.photos/seed/prop-002/600/400',
      description: 'Well-maintained house on North Road, close to schools and shopping centers.',
      agent_id: 'agent-002',
    },
    {
      id: 'prop-003',
      title: 'Bloomfield house',
      price: 250000,
      location: 'Ha Noi',
      category: 'house',
      type: 'for-rent',
      bedrooms: 4,
      bathrooms: 2,
      garages: 2,
      area: 850,
      status: 'For rent',
      image_url: 'https://picsum.photos/seed/prop-003/600/400',
      description: 'Spacious Bloomfield house available for rent, 4 bedrooms, great neighborhood.',
      agent_id: 'agent-003',
    },
    {
      id: 'prop-004',
      title: 'Rockville Ave villa',
      price: 180000,
      location: 'Da Nang',
      category: 'villa',
      type: 'for-sale',
      bedrooms: 5,
      bathrooms: 2,
      garages: 2,
      area: 320,
      status: 'For sale',
      image_url: 'https://picsum.photos/seed/prop-004/600/400',
      description: 'Elegant villa on Rockville Ave with private pool and landscaped garden.',
      agent_id: 'agent-001',
    },
    {
      id: 'prop-005',
      title: 'Scotch Plains villa',
      price: 160000,
      location: 'Nha Trang',
      category: 'villa',
      type: 'for-rent',
      bedrooms: 2,
      bathrooms: 2,
      garages: 2,
      area: 1200,
      status: 'For rent',
      image_url: 'https://picsum.photos/seed/prop-005/600/400',
      description: 'Beautiful villa for rent in Scotch Plains, ocean-view, fully furnished.',
      agent_id: 'agent-004',
    },
    {
      id: 'prop-006',
      title: 'Lees Creek house',
      price: 210000,
      location: 'TP HCM',
      category: 'house',
      type: 'for-sale',
      bedrooms: 3,
      bathrooms: 1,
      garages: 1,
      area: 480,
      status: 'For sale',
      image_url: 'https://picsum.photos/seed/prop-006/600/400',
      description: 'Cozy house near Lees Creek, renovated kitchen and open living space.',
      agent_id: 'agent-002',
    },
    {
      id: 'prop-007',
      title: 'Rockville Ave condominium',
      price: 120000,
      location: 'Ha Noi',
      category: 'apartment',
      type: 'for-sale',
      bedrooms: 2,
      bathrooms: 1,
      garages: 2,
      area: 100,
      status: 'For sale',
      image_url: 'https://picsum.photos/seed/prop-007/600/400',
      description: 'Modern condominium on Rockville Ave with city views and gym access.',
      agent_id: 'agent-003',
    },
    {
      id: 'prop-008',
      title: 'Ohio Scotch villa',
      price: 160000,
      location: 'Da Lat',
      category: 'villa',
      type: 'for-sale',
      bedrooms: 4,
      bathrooms: 2,
      garages: 3,
      area: 984,
      status: 'For sale',
      image_url: 'https://picsum.photos/seed/prop-008/600/400',
      description: 'Stunning villa in Da Lat highlands, cool climate, mountain views.',
      agent_id: 'agent-001',
    },
    {
      id: 'prop-009',
      title: 'Sulphur villa',
      price: 350000,
      location: 'Nha Trang',
      category: 'villa',
      type: 'for-sale',
      bedrooms: 3,
      bathrooms: 1,
      garages: 1,
      area: 480,
      status: 'For sale',
      image_url: 'https://picsum.photos/seed/prop-009/600/400',
      description: 'Premium beachfront villa in Nha Trang with direct sea access.',
      agent_id: 'agent-002',
    },
    {
      id: 'prop-010',
      title: 'Pawnee Ave apartment',
      price: 180000,
      location: 'TP HCM',
      category: 'apartment',
      type: 'for-sale',
      bedrooms: 2,
      bathrooms: 2,
      garages: 0,
      area: 220,
      status: 'For sale',
      image_url: 'https://picsum.photos/seed/prop-010/600/400',
      description: 'Central apartment on Pawnee Ave, walking distance to metro and markets.',
      agent_id: 'agent-004',
    },
    {
      id: 'prop-011',
      title: 'Oxford Ave apartment',
      price: 160000,
      location: 'Ha Noi',
      category: 'apartment',
      type: 'for-sale',
      bedrooms: 3,
      bathrooms: 2,
      garages: 0,
      area: 120,
      status: 'For sale',
      image_url: 'https://picsum.photos/seed/prop-011/600/400',
      description: 'Bright apartment on Oxford Ave, near business district and parks.',
      agent_id: 'agent-003',
    },
    {
      id: 'prop-012',
      title: 'Fremont Ave apartment',
      price: 210000,
      location: 'Da Nang',
      category: 'apartment',
      type: 'for-sale',
      bedrooms: 3,
      bathrooms: 2,
      garages: 0,
      area: 480,
      status: 'For sale',
      image_url: 'https://picsum.photos/seed/prop-012/600/400',
      description: 'Spacious apartment on Fremont Ave, modern design, sea-view balcony.',
      agent_id: 'agent-001',
    },
  ]);
};
